### PR TITLE
added onTap event

### PR DESCRIPTION
**Pull request by rodrigorafaeldamaceno**
Hello, thanks for this package, it has helped me a lot.

I had some problems implementing an onTap function, using gestures, so I realized that AndroidPdfViewer has support for this function, I just made the MethodChannel, android only.
You don't need to approve this PR, but it would be nice to bring this feature in new versions.

### CODE REVIEW

**Comment by andreBalh** [comment]
Your pr looks good so far, did you check if `onTap` is also available for iOS? @rodrigorafaeldamaceno

**Comment by rodrigorafaeldamaceno** [comment]
Good, I'm not familiar with swift and don't seen this for iOS, but it would be nice, I will try to do

**Comment by andreBalh** [comment]
Ok, next week, I could also check iOS @rodrigorafaeldamaceno

**Comment by andreBalh** [comment]
closing this by merging #58

**Comment by andreBalh** [comment]
Will be released with version `2.1.0` and works for android and ios @rodrigorafaeldamaceno 
Sry for the long wait!

**Pull request closed without merging**
